# Docs: https://gitee.com/paddlepaddle/PaddleOCR/blob/release/2.4/doc/doc_en/config_en.md?utm_source

Global:
  model_name: PP-OCRv5_server_rec # To use static model for inference.
  debug: false
  use_gpu: true
  epoch_num: 30 # Maximum training epoch number
  log_smooth_window: 20 # Log queue length, the median value in the queue each time will be printed
  print_batch_step: 10 # Set print log interval
  save_model_dir: ./output/germen_custom_PP-OCRv5_server_rec_18072025
  save_epoch_step: 2 # Set model save interval
  eval_batch_step: [0, 2000] # Set the model evaluation interval
  cal_metric_during_train: true # Set whether to evaluate the metric during the training process. At this time, the metric of the model under the current batch is evaluated
  calc_epoch_interval: 1
  pretrained_model: output/germen_custom_PP-OCRv5_server_rec_17072025/best_accuracy.pdparams #PP-OCRv5_server_rec_pretrained.pdparams # Set the path to the pretrained model
  checkpoints: # set model parameter path - Used to load parameters after interruption to continue training
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpgc
  character_dict_path: ./ppocr/utils/dict/german_dict.txt
  max_text_length: &max_text_length 25 # Set the maximum length of text
  infer_mode: false
  use_space_char: true # Set whether to recognize spaces
  distributed: true
  save_res_path: ./output/rec/german_predicts_ppocrv5.txt # Set the save address of the test model results
  d2s_train_image_shape: [3, 48, 320]


Optimizer:
  name: Adam # Optimizer class name
  beta1: 0.9 # Set the exponential decay rate for the 1st moment estimates
  beta2: 0.999 # Set the exponential decay rate for the 2nd moment estimates
  lr:
    name: Cosine # Set the learning rate decay class name
    learning_rate: 0.00015 # Set the initial learning rate
    warmup_epoch: 1 # Set the warmup epoch number
  regularizer:
    name: L2 # Set the regularization type
    factor: 3.0e-05 # Set the regularization factor


Architecture:
  model_type: rec
  algorithm: SVTR_HGNet
  Transform:
  Backbone:
    name: PPHGNetV2_B4
    text_rec: True
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: /mnt/ssd1/hang/OCR_Recoginition_data/line_boxes_dataset
    ext_op_transform_idx: 1
    label_file_list:
    - /mnt/ssd1/hang/OCR_Recoginition_data/line_boxes_dataset/train_split/train_00.txt
    - /mnt/ssd1/hang/OCR_Recoginition_data/line_boxes_dataset/train_split/train_01.txt
    # - /mnt/ssd1/hang/OCR_Recoginition_data/line_boxes_dataset/train_split/train_02.txt
    # - /mnt/ssd1/hang/OCR_Recoginition_data/line_boxes_dataset/train_split/train_03.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug:
        tia_prob: 0.5
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales: [[320, 32], [320, 48], [320, 64]]
    first_bs: &bs 200
    fix_bs: false
    divided_factor: [8, 16] # w, h
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: *bs
    drop_last: true # Whether to discard the last incomplete mini-batch because the number of samples in the data set cannot be divisible by batch_size
    num_workers: 16 # The number of sub-processes used to load data, if it is 0, the sub-process is not started, and the data is loaded in the main process
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /mnt/ssd1/hang/OCR_Recoginition_data/line_boxes_dataset/
    label_file_list:
    - /mnt/ssd1/hang/OCR_Recoginition_data/line_boxes_dataset/test_split/test_00.txt
    - /mnt/ssd1/hang/OCR_Recoginition_data/line_boxes_dataset/test_split/test_01.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 200
    num_workers: 4
